### ISSUE TITLE
astor/code_gen.py

### ISSUE THREAD

**Issue by gaushi** [kr-colab/popvae#10]
Hi @cjbattey 
FYI,
When I first installed 
I had issues with astor/code_gen.py with async being keyword in Python 3.7
I tried to fix it by changing async to is_async in code_gen.py
Popvae seems to work now (with example dataset in the repo).

Can you take a look and confirm what I noticed, or was I using wrong version of astor (I did everything according to instructions)?

Thanks,
Best regards,

**Comment by cjbattey** [comment]
Hi @gaushi! I've never run in to this issue myself. Actually I don't even know which dependency is importing the `astor` package (since it isn't directly imported by popvae), but this sounds like a possible issue with `astor` versioning in one of their setup scripts. Do you have a log of the original issue so I can try and find where the issue is?

**Comment by gaushi** [comment]
Hi @cjbattey 
I didn't keep the log of the original issue (my bad). After that fix I made, popvae seems to work fine (with example dataset and also with the test run that I had with my dataset). Sorry I could be of no further help in pointing out exact issue.
